version: '2'

services:

  app:
    restart: always
    container_name: app
    image: alpine
    volumes:
      - ./src:/usr/share/nginx/html
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/initdb.d:/docker-entrypoint-initdb.d
    command: /bin/true

  nginx-proxy:
    restart: always
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
