version: '2'

services:

  php:
    restart: always
    container_name: php
    build: ./etc
    ports:
      - "9000:9000"
    volumes_from:
      - app

  nginx:
    restart: always
    container_name: nginx
    image: nginx:alpine
    ports:
      - "10080:80"
      - "10443:443"
    links:
      - php
    volumes_from:
      - app
    environment:
      VIRTUAL_HOST: "xor.pics,*.xor.pics"
      HTTPS_METHOD: "noredirect" # not working ?

