version: '2'

services:
  app:
    container_name: app
    image: alpine
    volumes:
      - ./src:/usr/share/nginx/html
    command: /bin/true
  php:
    container_name: php
    build: ./etc
    ports:
      - "9000:9000"
    links:
      - database
    volumes_from:
      - app
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10080:80"
      - "10443:443"
    links:
      - php
    volumes_from:
      - app
    environment:
      VIRTUAL_HOST: "docker.loc,*.docker.loc"
  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes_from:
      - app
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: secret

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      VIRTUAL_HOST: "whoami.loc"
